# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RPLY_BIAS_SKY130NM
author:
  name: Carsten Wulff
  email: carsten@wulff.no

description: >- # this means to ignore newlines until "baseurl:"
    A PTAT current source
domain: "wulffern.github.io"
baseurl: "/rply_bias_sky130nm" # the subpath of your site, e.g. /blog
url: "https://wulffern.github.io" # the base hostname & protocol for your site, e.g. http://example.com


show_excerpts: false

minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/wulffern/rply_bias_sky130nm" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=uMepikoAAAAJ&hl=en&oi=ao" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/carsten-wulff-1855032/" }
    - { platform: twitter,        user_url: "https://twitter.com/cmoswulff" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@CarstenWulffNorway" }


# Build settings
markdown: kramdown
#theme: minima
#theme: architect
#remote_theme: pages-themes/architect@v0.2.0
#remote_theme: poole/hyde
remote_theme: wulffern/minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-remote-theme


#show_excerpts: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
